image: node:8.11

stages:
  - setup
  - test
  - coverage
  - build_image

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME

setup:
  stage: setup
  script:
    - yarn
  artifacts:
    paths:
      - node_modules
    expire_in: 20 minutes

test:
  stage: test
  script:
    - yarn test
    - yarn test:coverage
codecov:
  stage: coverage
  script:
    - npx codecov

build_image:
  stage: build_image
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

