language: node_js

node_js:
  - node
  - '6'
  - '10'

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test:coverage

after_success:
  - npx codecov

branches:
  only:
    - master
